services:
  spring-cli:
    container_name: spring-cli
    build:
      context: .
      dockerfile: Dockerfile

    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/springbootcli
      SPRING_DATASOURCE_USERNAME:
      SPRING_DATASOURCE_PASSWORD:
    ports:
        - "8080:8080"

    networks:
      - cobeliii

  db:
    container_name: spring-cli-postgres
    image: postgres:latest
    environment:
      POSTGRES_USER:
      POSTGRES_PASSWORD:
      POSTGRES_DB: springbootcli

    ports:
      - "5332:5432"
    restart: unless-stopped
    volumes:
      - db:/data/postgresql

    networks:
      - cobeliii

networks:
  cobeliii:
    driver: bridge

volumes:
  db:
